.\" Manpage for unitctl
.\"
.TH UNITCTL "1" "2022-12-29" "%%VERSION%%" "unitctl"
.SH NAME
unitctl \- NGINX UNIT Control Utility
.SH SYNOPSIS
unitctl [\fI\,FLAGS\/\fR] [\fI\,OPTIONS\/\fR] [\fI\,FILE\/\fR]...
.SH DESCRIPTION
WRITE ME
.
.SH "REPORTING BUGS"
Report any issues on the project issue tracker at:
.br
\fB<https://github.com/nginx/unit>\fR
.
.SH ACKNOWLEDGEMENTS
WRITE ME
.
.SH AUTHOR
Elijah Zupancic \fB<e.zupancic@f5.com>\fR
.
.SH COPYRIGHT
Copyright \(co 2022 F5. All Rights Reserved.
.br
License: Apache License 2.0 (Apache-2.0)
.br
Full License Text: <https://www.apache.org/licenses/LICENSE-2.0>
