name: ci
on: [push]
jobs:
  build_test:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "macos-10.15", "macos-11"]
        ipv6: ["", "--no-ipv6"]
        debug: ["", "--debug"]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt

      - name: configure
        run: ./configure ${{ipv6}} ${{debug}} --prefix=/usr 

      - name: compile
        run: make

      - name: test
        run: pytest test
2